language: java

jdk:
  - openjdk8

branches:
  only:
  - master
  - development

before_script: 
  - cd seip2020_practical_assignments  # enter Maven root directory
  - ls -la # this command just prints the contents of the current working directory.

after_success:
- echo "Nice job!"
